# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('time_parsing', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinHide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('pin_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_feed.Pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('pin_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_feed.Pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
