# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_feed', '0002_pinpublishthumblr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successOperation', models.BooleanField(default=True)),
            ],
        ),
    ]
