# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinterest_feed', '0003_settingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinPublishFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('pin_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_feed.Pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
